apiVersion: v1
kind: Namespace
metadata:
  name: hetzner-cloud
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: floatip
  namespace: hetzner-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: floatip
  namespace: hetzner-cloud
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: floatip
  namespace: hetzner-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: floatip
subjects:
- kind: ServiceAccount
  name: floatip
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: hetzner-cloud
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      serviceAccount: floatip
      containers:
        - name: floatip
          image: foosinn/floatip
          imagePullPolicy: Always
          env:
          - name: FLOATIP_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: FLOATIP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FLOATIP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
